export interface IEquipamento {
  id: number,
  tipo: string,
  equipamento: {
    numeroAlternador?: string,
    numeroMotor?: string,
    numero?:string,
    anoFabricacao?: string,
    potenciaEletrica?: string,
    potencia?: string,
    motor?:string,
    alternador?:string,
    uscaModelo?:string,
    tensao?: string,
    corrente?: string,
    modeloMotor?:string,
    modeloAlternador?:string,
    painelControle?:string,
    fabricante?:string,
    fatorPotencia?: string,
    frequencia?: string,
    horimetro?: number,
    tipoEquipamento:string,
    KWH?: number,
  },
  idCliente:number,
  horimetro_atual: number,
  KWH_atual: number,
 }

export interface IEquipamentoDetalhe {
  numeroAlternador?: string,
  numeroMotor?: string,
  numero?:string,
  anoFabricacao?: string,
  potenciaEletrica?: string,
  potencia?: string,
  motor?:string,
  alternador?:string,
  uscaModelo?:string,
  tensao?: string,
  corrente?: string,
  modeloMotor?:string,
  modeloAlternador?:string,
  painelControle?:string,
  fabricante?:string,
  fatorPotencia?:string,
  frequencia?: string,
  horimetro?: number,
  tipoEquipamento:string
  KWH?: number,
 }
